const countries = [
    { countryName: 'Andorra', code: '376' },
    { countryName: 'Afghanistan', code: '93' },
    { countryName: 'Antigua and Barbuda', code: '1268' },
    { countryName: 'Anguilla', code: '1264' },
    { countryName: 'Albania', code: '355' },
    { countryName: 'Armenia', code: '374' },
    { countryName: 'Angola', code: '244' },
    { countryName: 'Antarctica', code: '672' },
    { countryName: 'Argentina', code: '54' },
    { countryName: 'American Samoa', code: '1684' },
    { countryName: 'Austria', code: '43' },
    { countryName: 'Australia', code: '61' },
    { countryName: 'Aruba', code: '297' },
    { countryName: 'Åland Islands', code: '358' },
    { countryName: 'Azerbaijan', code: '994' },
    { countryName: 'Bosnia and Herzegovina', code: '387' },
    { countryName: 'Barbados', code: '1246' },
    { countryName: 'Bangladesh', code: '880' },
    { countryName: 'Belgium', code: '32' },
    { countryName: 'Burkina Faso', code: '226' },
    { countryName: 'Bulgaria', code: '359' },
    { countryName: 'Bahrain', code: '973' },
    { countryName: 'Burundi', code: '257' },
    { countryName: 'Benin', code: '229' },
    { countryName: 'Saint Barthélemy', code: '590' },
    { countryName: 'Bermuda', code: '1441' },
    { countryName: 'Brunei Darussalam', code: '673' },
    {
        countryName: 'Bolivia (Plurinational State of)',
        code: '591'
    },
    {
        countryName: 'Bonaire, Sint Eustatius and Saba',
        code: '5997'
    },
    { countryName: 'Brazil', code: '55' },
    { countryName: 'Bhutan', code: '975' },
    { countryName: 'Bouvet Island', code: '47' },
    { countryName: 'Botswana', code: '267' },
    { countryName: 'Belarus', code: '375' },
    { countryName: 'Belize', code: '501' },
    { countryName: 'Canada', code: '1' },
    { countryName: 'Switzerland', code: '41' },
    { countryName: "Côte d'Ivoire", code: '225' },
    { countryName: 'Chile', code: '56' },
    { countryName: 'Cameroon', code: '237' },
    { countryName: 'China', code: '86' },
    { countryName: 'Colombia', code: '57' },
    { countryName: 'Costa Rica', code: '506' },
    { countryName: 'Cuba', code: '53' },
    { countryName: 'Cabo Verde', code: '238' },
    { countryName: 'Curaçao', code: '599' },
    { countryName: 'Christmas Island', code: '61' },
    { countryName: 'Cyprus', code: '357' },
    { countryName: 'Germany', code: '49' },
    { countryName: 'Djibouti', code: '253' },
    { countryName: 'Denmark', code: '45' },
    { countryName: 'Dominica', code: '767' },
    { countryName: 'Algeria', code: '213' },
    { countryName: 'Ecuador', code: '593' },
    { countryName: 'Estonia', code: '372' },
    { countryName: 'Egypt', code: '20' },
    { countryName: 'Western Sahara', code: '212' },
    { countryName: 'Eritrea', code: '291' },
    { countryName: 'Spain', code: '34' },
    { countryName: 'Ethiopia', code: '251' },
    { countryName: 'Finland', code: '358' },
    { countryName: 'Fiji', code: '679' },
    {
        countryName: 'Micronesia (Federated States of)',
        code: '691'
    },
    { countryName: 'France', code: '33' },
    { countryName: 'Gabon', code: '241' },
    { countryName: 'Grenada', code: '1473' },
    { countryName: 'Georgia', code: '995' },
    { countryName: 'French Guiana', code: '594' },
    { countryName: 'Guernsey', code: '44' },
    { countryName: 'Ghana', code: '233' },
    { countryName: 'Gibraltar', code: '350' },
    { countryName: 'Greenland', code: '299' },
    { countryName: 'Guinea', code: '224' },
    { countryName: 'Guadeloupe', code: '590' },
    { countryName: 'Equatorial Guinea', code: '240' },
    { countryName: 'Greece', code: '30' },
    {
        countryName: 'South Georgia and the South Sandwich Islands',
        code: '500'
    },
    { countryName: 'Guatemala', code: '502' },
    { countryName: 'Guam', code: '1' },
    { countryName: 'Guinea-Bissau', code: '245' },
    { countryName: 'Guyana', code: '592' },
    { countryName: 'Hong Kong', code: '852' },
    { countryName: 'Honduras', code: '504' },
    { countryName: 'Croatia', code: '385' },
    { countryName: 'Haiti', code: '509' },
    { countryName: 'Hungary', code: '36' },
    { countryName: 'Indonesia', code: '62' },
    { countryName: 'Ireland', code: '353' },
    { countryName: 'Israel', code: '972' },
    { countryName: 'Isle of Man', code: '44' },
    { countryName: 'India', code: '91' },
    { countryName: 'Iraq', code: '964' },
    {
        countryName: 'Iran (Islamic Republic of)',
        code: '98'
    },
    { countryName: 'Iceland', code: '354' },
    { countryName: 'Italy', code: '39' },
    { countryName: 'Jersey', code: '44' },
    { countryName: 'Jamaica', code: '876' },
    { countryName: 'Jordan', code: '962' },
    { countryName: 'Japan', code: '81' },
    { countryName: 'Kenya', code: '254' },
    { countryName: 'Kyrgyzstan', code: '996' },
    { countryName: 'Cambodia', code: '855' },
    { countryName: 'North Korea', code: '850' },
    { countryName: 'South Korea', code: '82' },
    { countryName: 'Kiribati', code: '686' },
    { countryName: 'Saint Kitts and Nevis', code: '1869' },
    { countryName: 'Kuwait', code: '965' },
    { countryName: 'Kazakhstan', code: '7' },
    { countryName: 'Lebanon', code: '961' },
    { countryName: 'Saint Lucia', code: '1758' },
    { countryName: 'Liechtenstein', code: '423' },
    { countryName: 'Sri Lanka', code: '94' },
    { countryName: 'Liberia', code: '231' },
    { countryName: 'Lesotho', code: '266' },
    { countryName: 'Lithuania', code: '370' },
    { countryName: 'Luxembourg', code: '352' },
    { countryName: 'Latvia', code: '371' },
    { countryName: 'Libya', code: '218' },
    { countryName: 'Morocco', code: '212' },
    { countryName: 'Monaco', code: '377' },
    { countryName: 'Montenegro', code: '382' },
    {
        countryName: 'Saint Martin (French part)',
        code: '590'
    },
    { countryName: 'Madagascar', code: '261' },
    { countryName: 'Mali', code: '223' },
    { countryName: 'Myanmar', code: '95' },
    { countryName: 'Mongolia', code: '976' },
    { countryName: 'Macao', code: '853' },
    { countryName: 'Martinique', code: '596' },
    { countryName: 'Mauritania', code: '222' },
    { countryName: 'Montserrat', code: '1664' },
    { countryName: 'Malta', code: '356' },
    { countryName: 'Mauritius', code: '230' },
    { countryName: 'Maldives', code: '960' },
    { countryName: 'Malawi', code: '265' },
    { countryName: 'Mexico', code: '52' },
    { countryName: 'Malaysia', code: '60' },
    { countryName: 'Mozambique', code: '258' },
    { countryName: 'Namibia', code: '264' },
    { countryName: 'New Caledonia', code: '687' },
    { countryName: 'Norfolk Island', code: '672' },
    { countryName: 'Nigeria', code: '234' },
    { countryName: 'Nicaragua', code: '505' },
    { countryName: 'Norway', code: '47' },
    { countryName: 'Nepal', code: '977' },
    { countryName: 'Nauru', code: '674' },
    { countryName: 'Niue', code: '683' },
    { countryName: 'New Zealand', code: '64' },
    { countryName: 'Oman', code: '968' },
    { countryName: 'Panama', code: '507' },
    { countryName: 'Peru', code: '51' },
    { countryName: 'French Polynesia', code: '689' },
    { countryName: 'Papua New Guinea', code: '675' },
    { countryName: 'Pakistan', code: '92' },
    { countryName: 'Poland', code: '48' },
    {
        countryName: 'Saint Pierre and Miquelon',
        code: '508'
    },
    { countryName: 'Pitcairn', code: '64' },
    { countryName: 'Puerto Rico', code: '1' },
    { countryName: 'Palestine, State of', code: '970' },
    { countryName: 'Portugal', code: '351' },
    { countryName: 'Palau', code: '680' },
    { countryName: 'Paraguay', code: '595' },
    { countryName: 'Qatar', code: '974' },
    { countryName: 'Réunion', code: '262' },
    { countryName: 'Romania', code: '40' },
    { countryName: 'Serbia', code: '381' },
    { countryName: 'Russia', code: '7' },
    { countryName: 'Rwanda', code: '250' },
    { countryName: 'Saudi Arabia', code: '966' },
    { countryName: 'Solomon Islands', code: '677' },
    { countryName: 'Seychelles', code: '248' },
    { countryName: 'Sweden', code: '46' },
    { countryName: 'Singapore', code: '65' },
    {
        countryName: 'Saint Helena, Ascension and Tristan da Cunha',
        code: '290'
    },
    { countryName: 'Slovenia', code: '386' },
    { countryName: 'Svalbard and Jan Mayen', code: '4779' },
    { countryName: 'Slovakia', code: '421' },
    { countryName: 'Sierra Leone', code: '232' },
    { countryName: 'Republic of San Marino', code: '378' },
    { countryName: 'Senegal', code: '221' },
    { countryName: 'Somalia', code: '252' },
    { countryName: 'Suriname', code: '597' },
    { countryName: 'South Sudan', code: '211' },
    { countryName: 'Sao Tome and Principe', code: '239' },
    { countryName: 'El Salvador', code: '503' },
    {
        countryName: 'Sint Maarten (Dutch part)',
        code: '1721'
    },
    { countryName: 'Syrian Arab Republic', code: '963' },
    { countryName: 'Chad', code: '235' },
    { countryName: 'Togo', code: '228' },
    { countryName: 'Thailand', code: '66' },
    { countryName: 'Tajikistan', code: '992' },
    { countryName: 'Tokelau', code: '690' },
    { countryName: 'Timor-Leste', code: '670' },
    { countryName: 'Turkmenistan', code: '993' },
    { countryName: 'Tunisia', code: '216' },
    { countryName: 'Tonga', code: '676' },
    { countryName: 'Turkey', code: '90' },
    { countryName: 'Trinidad and Tobago', code: '868' },
    { countryName: 'Tuvalu', code: '688' },
    {
        countryName: 'United Republic of Tanzania',
        code: '255'
    },
    { countryName: 'Ukraine', code: '380' },
    { countryName: 'Uganda', code: '256' },
    { countryName: 'United States of America', code: '1' },
    { countryName: 'Uruguay', code: '598' },
    { countryName: 'Uzbekistan', code: '998' },
    {
        countryName: 'Saint Vincent and the Grenadines',
        code: '1784'
    },
    {
        countryName: 'Venezuela (Bolivarian Republic of)',
        code: '58'
    },
    {
        countryName: 'Virgin Islands (British)',
        code: '1284'
    },
    { countryName: 'Virgin Islands (U.S.)', code: '1340' },
    { countryName: 'Vietnam', code: '84' },
    { countryName: 'Vanuatu', code: '678' },
    { countryName: 'Wallis and Futuna', code: '681' },
    { countryName: 'Samoa', code: '685' },
    { countryName: 'Yemen', code: '967' },
    { countryName: 'Mayotte', code: '262' },
    { countryName: 'South Africa', code: '27' },
    { countryName: 'Zambia', code: '260' },
    { countryName: 'Zimbabwe', code: '263' },
    { countryName: 'Eswatini', code: '268' },
    { countryName: 'North Macedonia', code: '389' },
    { countryName: 'Philippines', code: '63' },
    { countryName: 'Netherlands', code: '31' },
    { countryName: 'United Arab Emirates', code: '971' },
    { countryName: 'Republic of Moldova', code: '373' },
    { countryName: 'Gambia', code: '220' },
    { countryName: 'Dominican Republic', code: '1' },
    { countryName: 'Sudan', code: '249' },
    {
        countryName: "Lao People's Democratic Republic",
        code: '856'
    },
    {
        countryName: 'Taiwan, Province of China',
        code: '886'
    },
    { countryName: 'Republic of the Congo', code: '242' },
    { countryName: 'Czechia', code: '420' },
    { countryName: 'United Kingdom', code: '44' },
    { countryName: 'Niger', code: '227' },
    {
        countryName: 'Democratic Republic of the Congo',
        code: '243'
    },
    {
        countryName: 'Commonwealth of The Bahamas',
        code: '1 242'
    },
    {
        countryName: 'Cocos (Keeling) Islands',
        code: '61 891'
    },
    {
        countryName: 'Central African Republic',
        code: '236'
    },
    { countryName: 'Cook Islands', code: '682' },
    { countryName: 'Falkland Islands', code: '500' },
    { countryName: 'Faroe Islands', code: '298' },
    {
        countryName: 'Territory of Heard Island and McDonald Islands',
        code: '672'
    },
    {
        countryName: 'British Indian Ocean Territory',
        code: '246'
    },
    { countryName: 'Comoros', code: '269' },
    { countryName: 'Cayman Islands', code: '1 345' },
    {
        countryName: 'Republic of the Marshall Islands',
        code: '692'
    },
    {
        countryName: 'Commonwealth of the Northern Mariana Islands',
        code: '1 670'
    },
    {
        countryName: 'Turks and Caicos Islands',
        code: '1 649'
    },
    {
        countryName: 'French Southern and Antarctic Lands',
        code: '672'
    },
    {
        countryName: 'United States Minor Outlying Islands',
        code: '246'
    },
    { countryName: 'Holy See', code: '39' },
    { countryName: 'Republic of Kosovo', code: '383' },
    { countryName: 'Netherlands Antilles', code: '599' },
]


export default countries